### ISSUE TITLE
Change Button style

### ISSUE THREAD

**Issue by kelvinparmar** [kelvinparmar/Hulu-clone#3]
![12](https://user-images.githubusercontent.com/94775043/226515747-336fd404-c361-4ca2-a6a6-bf9b29dd4b9b.JPG)

**Comment by ChiragSharma0208** [comment]
Could you please assign this problem to me?

**Comment by kelvinparmar** [comment]
@ChiragSharma0208 
Sorry that issue was completed yesterday
Please go with another issue
