### ISSUE TITLE
Improve UI of Login Page

### ISSUE THREAD

**Issue by KeyurGK** [kelvinparmar/Hulu-clone#8]
I want to contribute to this project, by improving the UI of the Login page. Looking forward to getting assigned.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/56074740/230888415-797c2a0b-6b79-49e8-9fe8-4c892fe5d4b7.png">

**Comment by kelvinparmar** [comment]
@KeyurGK 
Sure you can go ahead
